name: appatube
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  youtube_explode_dart: ^3.0.5
  audio_service: ^0.18.12
  just_audio: ^0.9.36
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  dio: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  miniplayer: ^1.0.1
  permission_handler: ^11.3.0
  rxdart: ^0.27.7
  youtube_player_flutter: ^9.1.1
  google_generative_ai: ^0.4.3
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.3
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "src/appa.png"
  adaptive_icon_background: "#0A0A0A"
  adaptive_icon_foreground: "src/appa.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - .env
    - src/appa.png
    - src/appaagent.jpg
